###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileBrowser = thunar
$menu = fuzzel
$browser = flathub run app.zen_browser.zen
$scripts = $HOME/.config/scripts
